name: Deploy CPU Stress Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      run: |
        sudo apt-get install -y awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Package and upload CloudFormation templates
      run: |
        aws s3 cp templates/ s3://${{ secrets.S3_BUCKET }}/templates/ --recursive

    - name: Create CloudFormation stack
      run: |
        aws cloudformation create-stack --stack-name cpu-stress-stack --template-url https://${{ secrets.S3_BUCKET }}.s3.amazonaws.com/templates/main.yaml --parameters file://parameters/parameters.json --capabilities CAPABILITY_IAM

    - name: Wait for stack creation
      run: |
        aws cloudformation wait stack-create-complete --stack-name cpu-stress-stack

    - name: Output stack information
      run: |
        aws cloudformation describe-stacks --stack-name cpu-stress-stack --query "Stacks[0].Outputs" --output table